name: third_eye
description: "Third Eye mobile app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.4.0
  webview_flutter: ^4.0.0
  url_launcher: ^6.3.1
  intl: ^0.20.2  # Add the intl package here
  fl_chart: ^0.70.2
  provider: ^6.1.2   # For state management


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/font/Orbitron-Regular.ttf

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/font/Orbitron-Regular.ttf
